version: '3.1'

services:
  php:
    build: 
      context: ./php
    # volumes:
    #   - ./www/public:/var/www
    # restart: always  
    ports:
      - "8082:80"
   
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: cities
    ports:
      - "5432:5432"


  adminer:

    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  db: